### ISSUE TITLE
Refactor the movetext validation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#177]
The movetext validation should be refactored so that chess games ending in any of the following combination of characters will pass the validation process as well:

- 1–0
- 1/2–1/2
- ½–½
- 0–1

Please note how the above, which are non-standard, differ from the PGN standard ones.

- 1-0
- 1/2-1/2
- 0-1

The thing is, non-standard PGN notation is typically found on websites like Wikipedia to describe game results. Thus, chances are that users will copy and paste games containing those as it is shown in the GIF below.

![figure-01](https://user-images.githubusercontent.com/4062000/150343953-549d96cd-f0c2-4c87-b564-b79f1a5bb1a0.gif)
**Figure 1**. Loading World Chess Championship 2021 games from Wikipedia.

Happy learning, and keep it up.

**Comment by MarcinGladkowski** [comment]
Hi! I will working on it. 

PR: https://github.com/chesslablab/php-chess/pull/214

Review, please.

Have a nice day!

**Comment by programarivm** [comment]
@MarcinGladkowski welcome to ChesslabLab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/php-chess/blob/master/CONTRIBUTING.md).

Keep it up, and happy learning and coding!
