### ISSUE TITLE
Implement the bad bishop evaluation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#208]
A new evaluation feature needs to be implemented in order to keep track of bad bishops. A bad bishop is a bishop whose mobility is restricted by its own pawns. Sometimes it becomes such a bad piece that it's like playing with one less piece. 

Thus, a new file named `BadBishopEvaluation.php` needs to be implemented in a similar way as other evaluation features, for example:

- [src/Evaluation/BishopOutpostEvaluation](https://github.com/chesslablab/php-chess/blob/master/src/Evaluation/BishopOutpostEvaluation.php)
- [src/Evaluation/DoubledPawnEvaluation](https://github.com/chesslablab/php-chess/blob/master/src/Evaluation/DoubledPawnEvaluation.php)

Also `Chess\Evaluation\BadBishopEvaluation` should be TDDed accordingly:

- [tests/unit/Evaluation/BishopOutpostEvaluationTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Evaluation/BishopOutpostEvaluationTest.php)
- [tests/unit/Evaluation/DoubledPawnEvaluationTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Evaluation/DoubledPawnEvaluationTest.php)

With the new feature implemented, we'll be able to display a nice bar chart pointing out whether or not a bad bishop is found on the chessboard. 

For further information please visit:

- [What Does It Mean to TDD a Class?](https://bootcamp.uxdesign.cc/what-does-it-mean-to-tdd-a-class-4dbb9bd6b5e2)
- [Learn to Play Like a Chess Master](https://programarivm.medium.com/learn-to-play-like-a-chess-master-4bc31f93ebf2)

Keep it up, and happy coding and learning!

**Comment by programarivm** [comment]
Hi @MarcinGladkowski,

Let's try to define what a bad bishop is in terms of the pawns on its side only, this way it'll be differentiated from a blocked bishop I suppose. Here are some hints to understand what a bad bishop is:

- If most of your pawns are on light squares, then the light-squared bishop can be restricted (the same is true for dark-squared bishops and pawns on dark squares)

- If you have just one bishop, you should try to place your pawns on the squares of the opposite color of your bishop. If you do this, then you can control squares of both colors, and your bishop can move more freely

- The rule of thumb claims that a bishop suffers if the pawns are blocked and stand on squares of the colour the bishop moves on.  If the bishop is not hemmed in by his own pawns we speak of a "good  bishop"

Thus, what about creating a bunch of tests showing specific results for chess positions according to these hints?

For further information please visit:

- [Understanding before Moving 43: Good bishops, bad bishops](https://en.chessbase.com/post/understanding-before-moving-43-good-bishops-bad-bishops) 
- [Bad Bishop](https://www.chess.com/terms/bad-bishop)

Happy learning and coding!

**Comment by programarivm** [comment]
This is a suggested result for the following sample position:

![chessboard](https://user-images.githubusercontent.com/4062000/180267173-b1d9c1f7-e48e-4097-a0ed-72a88b3d0f86.png)

White's bishop is being blocked by 0 pawns while Black's bishop is blocked by 5 pawns.

```php
<?php

namespace Chess\Tests\Unit\Eval;

use Chess\Eval\BadBishopEval;
use Chess\FEN\StrToBoard;
use Chess\Tests\AbstractUnitTestCase;

class BadBishopEvalTest extends AbstractUnitTestCase
{
    /**
     * @test
     */
    public function position_01()
    {
        $fen = '8/5b2/p2k4/1p1p1p1p/1P1K1P1P/2P1PB2/8/8 w - - 0 1';

        $board = (new StrToBoard($fen))->create();

        $expected = [
            'w' => 0,
            'b' => 5,
        ];

        $badBishopEval = (new BadBishopEval($board))->eval();

        $this->assertSame($expected, $badBishopEval);
    }
}
```

**Comment by MarcinGladkowski** [comment]
Great! Thanks for that example. I will prepare solution for it.

Happy learning and coding!

**Comment by programarivm** [comment]
Thank you! 

Shall we do it test by test? 

I just found [this position](https://thechessworld.com/articles/middle-game/the-bad-bishop/) with a bad bishop on c2 and was wondering which expected result would make sense.

![2-1-300x300](https://user-images.githubusercontent.com/4062000/180307865-e828f817-5cdb-4dcf-8394-14a0a32e268d.jpg)


Keep it up,

**Comment by programarivm** [comment]
This is [a position](https://www.researchgate.net/figure/Classical-example-of-a-bad-bishop_fig1_225706084) with a bad bishop on d7. Which result should be expected?

![chess-position](https://user-images.githubusercontent.com/4062000/180310135-215e71af-bf48-470b-9e67-c51173d938b7.png)

**Comment by programarivm** [comment]
This is a bad bishop on c8.
![chess-position](https://user-images.githubusercontent.com/4062000/180311254-28e2ea66-418f-4167-88a3-42624036488b.png)

**Comment by programarivm** [comment]
@MarcinGladkowski the samples have been updated with an expected result if that makes sense.
