### ISSUE TITLE
Long notation

### ISSUE THREAD

**Issue by StepHaze** [chesslablab/php-chess#230]
Thank you for your project!

Is it possible to enter a move not only by:
$game->play('w', 'e4');

but also:
$game->play('w', 'e2e4');

**Comment by programarivm** [comment]
Let's implement the so-called [long algebraic notation](https://en.wikipedia.org/wiki/Algebraic_notation_(chess)#Long_algebraic_notation)! 

According to Wikipedia:

> A form of long algebraic notation (without piece names) is also used by the [Universal Chess Interface (UCI)](https://en.wikipedia.org/wiki/Universal_Chess_Interface) standard.

Keep it up,
