### ISSUE TITLE
does it work with PHP 8.1 ?

### ISSUE THREAD

**Issue by StepHaze** [chesslablab/php-chess#231]
When I try to run this code:

use Chess\Game;

$game = new Game();

$game->play('w', 'e4');
$game->play('b', 'e5');

I get this error message:

PHP Fatal error:  Uncaught TypeError: Cannot assign null to property Chess\Game::$variant of type string in /home/haze/www/html/proj/ch2/vendor/chesslablab/php-chess/src/Game.php:83
Stack trace:
#0 /home/haze/www/html/proj/ch2/index.php(5): Chess\Game->__construct()
#1 {main}
  thrown in /home/haze/www/html/proj/ch2/vendor/chesslablab/php-chess/src/Game.php on line 83

Process finished with exit code 255

**Comment by programarivm** [comment]
Sorry the docs should be updated, meanwhile please check out the tests at [tests/unit/GameTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/GameTest.php).

```php
$game = new Game(
    Game::VARIANT_CLASSICAL,
    Game::MODE_ANALYSIS
);
```
Thanks!

**Comment by StepHaze** [comment]
Thank you!
