### ISSUE TITLE
Oddity and warnings when installing with Composer

### ISSUE THREAD

**Issue by vesper8** [chesslablab/php-chess#237]
Just tried installing with Composer and noticed these two warnings.

`composer require chesslablab/php-chess`

```
Failed to extract chesslablab/php-chess: (1) '/usr/bin/unzip' -qq '/redacted/vendor/composer/tmp-f3fd3559e4f7a748f1afbf4c9161b9c7' -d '/redacted/vendor/composer/22c759f8'

replace /redacted/vendor/composer/22c759f8/chesslablab-php-chess-5e5ec33/img/pieces/png/375/b.png? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
```

and

```
Class Chess\ML\Supervised\Regression\PermutationPredictor located in ./vendor/chesslablab/php-chess/src/ML/Supervised/Regression/GeometricSumPredictor.php does not comply with psr-4 autoloading standard. Skipping.
```

And then using `composer info` I noticed that `1.2.15` was installed instead of the latest which currently is `1.2.51`

Not sure what I'm doing wrong. I'm running PHP 8.1 on Mac Monterey

**Comment by vesper8** [comment]
Noticed that even though my system was running on PHP 8.1, I had a platform constraint in my composer.json that would limit it to PHP 8.0

Removed that, and this time was able to install `1.2.50`

The second warning is now gone, but the first warning remains

**Comment by standan-hulk** [comment]
The first warning seems to be related to https://github.com/chesslablab/php-chess/issues/246

```The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class```
