### ISSUE TITLE
TDD the Capablanca chessboard

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#242]
Let's implement a new chess variant!

According to Wikipedia:

> Capablanca believed that chess would be played out in a few decades (meaning games between grandmasters would always end in draws).

[Chess\Variant\Capablanca\Board](https://github.com/chesslablab/php-chess/blob/master/src/Variant/Capablanca/Board.php) is being implemented using a test-driven development approach. The following chess position needs to be tested in [tests/unit/Variant/Capablanca/BoardTest.php](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Variant/Capablanca/BoardTest.php) after playing `1.Nj3 e7 2.Ci3 Nc8 3.h3 b8 4.Bh2 Ci8 5.O-O` 

```
 r  .  a  b  q  k  b  .  n  r 
 p  .  p  p  .  p  p  p  p  p 
 .  p  n  .  .  .  .  .  c  . 
 .  .  .  .  p  .  .  .  .  . 
 .  .  .  .  .  .  .  .  .  . 
 .  .  .  .  .  .  .  .  .  . 
 .  .  .  .  .  .  .  .  .  . 
 .  .  .  .  .  .  .  P  C  N 
 P  P  P  P  P  P  P  B  P  P 
 R  N  A  B  Q  .  .  R  K  .
```

More specifically, an array called `$expected` needs to be added in `play_Nj3_e7_Ci3_Nc8_h3_b8_Bh2_Ci8_O_O()` to make this test pass.

Keep it up, and happy coding and learning.

**Comment by SimonUR** [comment]
Hey, chesslablab,

would love to contribute. Can you assign me this Issue.

Best regards,
Simon
