### ISSUE TITLE
Assets being deleted when pulling down the repository on Windows

### ISSUE THREAD

**Issue by RoadSigns** [chesslablab/php-chess#246]
When I try and pull down the repository and open it up on Windows all of the chess piece assets with lowercase filenames delete themselves.

This is due to the naming of the pieces being `p.png` and `P.png`.

Not sure if this is something you want to look into to support.

**Comment by standan-hulk** [comment]
I'm facing the same issue:

![image](https://user-images.githubusercontent.com/82732185/195956726-1b00f1d6-e136-46be-95b9-f5126333ef28.png)

The png files should be renamed with a speaking and unique name.

**Comment by Maikuolan** [comment]
@RoadSigns @standan-hulk PR sent (#253).
