### ISSUE TITLE
Call to undefined function Chess\Variant\Classical\msgpack_unpack()

### ISSUE THREAD

**Issue by MikePageDev** [chesslablab/php-chess#375]
Hello, I have just tried this package with the below code and received this error. 

```
$board = new Board();
$board->play('w', 'e4');
```

I don't know what went wrong. Would appreciate some guidance.

**Comment by programarivm** [comment]
The MessagePack PECL extension needs to be installed.

```
pecl install msgpack
```

See:

- https://github.com/chesslablab/php-chess/issues/365

Keep it up,

**Comment by MikePageDev** [comment]
Are you aware that there is a PHP package available that can be installed with composer
https://github.com/rybakit/msgpack.php
Would it be better to use that?

**Comment by MikePageDev** [comment]
Hello, I have forked the package and tried to replace the need for the extension and replace it with the above php package. Unfortunately when running the tests there where 19 failures. I don't believe I have the knowledge to work out what went wrong. I use Lando for my development environment, I have tried to install the extension with no success. If you have any pointers please let me know.

**Comment by programarivm** [comment]
Thank you @MikePageDev for the feedback , it is very much appreciated!

Not too sure about replacing the PECL extension with rybakit/msgpack at this moment.

Let me point out the following:

- Try to [install the PHP extension on Lando](https://docs.lando.dev/php/installing-extensions.html)
- Ask the Lando team for [support](https://lando.dev/support)
- Try to setup the PHP environment on your machine without Lando

BTW, did you try to install the PHP extension on your machine or on Lando? 

Happy coding and learning!

**Comment by programarivm** [comment]
Also the [chess-api/Dockerfile](https://github.com/chesslablab/chess-api/blob/main/Dockerfile) is an example on how to install the PECL msgpack extension.

```
RUN pecl install msgpack \
    && docker-php-ext-enable msgpack
```

I hope this will be helpful.

**Comment by MikePageDev** [comment]
@programarivm Thank you for getting back to me. I tried installing it in the Lando container using the lando.yml file as well as ssh into the container. When I ran `docker-php-ext-enable msgpacl` I got the following error

`OCI runtime exec failed: exec failed: unable to start container process: exec: "docker-php-enable": executable file not found in $PATH: unknown`

I think I may need to add `extension=msgpack.so` to php.ini which means I need to do a custom php.ini.

I don't have php installed locally because I have always used Lando. 

BTW thank you for the invite to ChesslaBlab

**Comment by programarivm** [comment]
@MikePageDev welcome to ChesslabLab, 

Thank you for joining the community! 

Installing PHP on your local machine is a breeze.

What OS are you using?

**Comment by MikePageDev** [comment]
Thank you

I am on Linux.

I have now got msgpack installed on Lando but I am still getting the `Call to undefined function Chess\Variant\Classical\msgpack_unpack()` error.

**Comment by MikePageDev** [comment]
I have tried install it locally but get the following error `No releases available for package "pecl.php.net/mspack"`

**Comment by programarivm** [comment]
Have you tried entering this before?

```
pear clear-cache
pear update-channels
pear upgrade
```

**Comment by MikePageDev** [comment]
Yes no joy

**Comment by programarivm** [comment]
@MikePageDev this is an excellent opportunity to learn about installing PECL extensions on Linux!

Keep it up,
