### ISSUE TITLE
Unit test the Fianchetto Variation of the Benoni Defense

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#42]
This issue is intended to practice some unit testing skills.

A new chess opening needs to be added as the following examples:

- [`BenkoGambit.php`](https://github.com/chesslab/php-chess/blob/master/tests/Sample/Opening/Benoni/BenkoGambit.php)
- [`Open.php`](https://github.com/chesslab/php-chess/blob/master/tests/Sample/Opening/Sicilian/Open.php)

Specifically, the [Fianchetto Variation of the Benoni Defense](https://en.wikipedia.org/wiki/Benoni_Defense) should be tested:

`1.d4 Nf6 2.c4 c5 3.d5 e6 4.Nc3 exd5 5.cxd5 d6 6.Nf3 g6 7.g3 Bg7 8.Bg2 0-0 9.0-0 Nbd7 10.Nd2 a6 11.a4 Re8`

Happy learning and coding!

**Comment by vikeng** [comment]
Hi programarivm! Assign me to this issues, please!

**Comment by programarivm** [comment]
Thank you @vikeng, keep it up!

**Comment by vikeng** [comment]
Hi, @programarivm!
I sent this commit. I also made two tests for this opening, similar to the BenkoGambit

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/php-chess/pull/46
