### ISSUE TITLE
Unit test the Classical Variation of the French Defense

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#43]
This issue is intended to practise some unit testing skills.

A new chess opening needs to be added as the following example:

- [`LucenaDefense.php`](https://github.com/chesslab/php-chess/blob/master/tests/Sample/Opening/RuyLopez/LucenaDefense.php)

Specifically, the [Classical Variation of the French Defense](https://en.wikipedia.org/wiki/French_Defence#Classical_Variation:_3...Nf6) should be tested:

`1.e4 e6 2.d4 d5 3.Nc3 Nf6`

Happy learning and coding!

**Comment by Victoria-DR** [comment]
Hi there, happy learning and coding! I'd like to work on this issue.

**Comment by programarivm** [comment]
@Victoria-DR, welcome to ChesslabLab.

Thank you for joining the community.

Please make sure to read the [Contributing Guidelines](https://medium.com/geekculture/how-to-contribute-to-chesslab-cca73fefaf70).

Keep it up, and happy learning and coding!

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/php-chess/pull/73
