### ISSUE TITLE
Unit test the Exchange Variation of the French Defense

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#44]
This issue is intended to practise some unit testing skills.

A new chess opening needs to be added as the following example:

- [`LucenaDefense.php`](https://github.com/chesslab/php-chess/blob/master/tests/Sample/Opening/RuyLopez/LucenaDefense.php)

Specifically, the [Exchange Variation of the French Defense](https://en.wikipedia.org/wiki/French_Defence#Exchange_Variation:_3.exd5_exd5) should be tested:

`1.e4 e6 2.d4 d5 3.exd5 exd5`

Happy learning and coding!

**Comment by 11slartibartfast** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
Since this one is labelled with `hacktoberfest` too it'll be assigned to you on October 1st if this is okay.

I can't wait to see what you come up with!

Keep it up.
