### ISSUE TITLE
Unit test the Symmetrical Defense to the Queen's Gambit

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#45]
This issue is intended to practise some unit testing skills.

A new chess opening needs to be added as the following example:

- [`LucenaDefense.php`](https://github.com/chesslab/php-chess/blob/master/tests/Sample/Opening/RuyLopez/LucenaDefense.php)

Specifically, the [Symmetrical Defense to the Queen's Gambit](https://en.wikipedia.org/wiki/Symmetrical_Defense) should be tested:

`1.d4 d5 2.c4 c5`

Happy learning and coding!

**Comment by SimonUR** [comment]
Hey, 
Can you assign me to this issue ? Would like to contribute. 😄

**Comment by programarivm** [comment]
@SimonUR, welcome to ChesslabLab.

Thank you for joining the community.

Happy learning and coding!

**Comment by SimonUR** [comment]
Hi, @programarivm!
I sent this commit. I also made a hsitroy test for this opening, similar to the Lucena Defense.

**Comment by programarivm** [comment]
Thanks @SimonUR for sending your first PR, it looks good!

One test is failing if I'm not very much mistaken. 

Keep it up and please let us know if you have any questions. ChesslabLab members are encouraged to break things and learn from mistakes. 

We are here to practice skills, thanks!

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/php-chess/pull/60

**Comment by programarivm** [comment]
Thank you @SimonUR, probably you may want to ascii test the chess opening in a similar way as with https://github.com/chesslablab/php-chess/issues/47

Please let me know if you'd want to be assigned a new issue and I'll create it for you within the next days. 

Now having a break. Have a nice day!
