### ISSUE TITLE
En Passant Capture Square Incorrectly Identified

### ISSUE THREAD

**Issue by tpikri** [chesslablab/php-chess#451]
Hello!! I love this library and it seems to be pretty versatile, implementing all the game logic with all the details, special moves and extras.
I think I found an issue.

**Issue:**
The current implementation of the capture method in [Variant/Classical/Board.php](https://github.com/chesslablab/php-chess/blob/master/src/Variant/Classical/Board.php#L566) incorrectly identifies the square for en passant capture. That results in capture not being made (though the move is made). The issue lies in attempting to capture the pawn on the en passant destination square, whereas, in en passant, the pawn to capture is on a different square.

**Proposed Solution:**
Modify the capture method to use the correct square for en passant capture. Utilize the getEnPassantCaptureSq or similar method of the [Piece/P.php](https://github.com/chesslablab/php-chess/blob/master/src/Piece/P.php) class, ensuring that the correct square is identified for capturing the pawn during en passant. For white pawns the capture square should be one rank lower from the en passant square and for black pawns that should be one rank higher.

Note that I'm a rookie in git, maybe in general, so take what I say with a grain of salt.
Happy learning and coding!
Cheers!!

**Comment by programarivm** [comment]
Hi @tpikri,

Thank you for opening this issue. Let's write a new test for it, can you please provide a chess position in FEN format?

Keep it up,

**Comment by tpikri** [comment]
An example in FEN could be
`r1bqkbnr/p3pppp/8/1Pp5/8/8/P1PPPPPP/RNBQKBNR w KQkq c6 0 1`
and then move b5 to c6. A capture should be made on c5 square.

```php
use Chess\Variant\Classical\Board;
use Chess\FenToBoard;

$board = FenToBoard::create('r1bqkbnr/p3pppp/8/1Pp5/8/8/P1PPPPPP/RNBQKBNR w KQkq c6 0 1');
echo nl2br($board->toAsciiString());
echo '<br><br>--- b5 to c6 - en passant capture of c5 ---<br><br>';
$board->playLan('w', 'b5c6');
echo nl2br($board->toAsciiString());
```
