### ISSUE TITLE
🖦 TDD the Chess\Eval\DeflectionEval class

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#458]
A new evaluation feature called `Chess\Eval\DeflectionEval` needs to be implemented in the [php-chess/src/Eval](https://github.com/chesslablab/php-chess/tree/master/src/Eval) folder. The PHPUnit tests are to be written in the `php-chess/tests/unit/Eval/DeflectionEvalTest.php` file accordingly.

See:

- [Deflection (chess)](https://en.wikipedia.org/wiki/Deflection_(chess))

**Comment by over-light** [comment]
I'll help you with implementing the new evaluation feature called DeflectionEval in the php-chess/src/Eval folder. We'll also create the corresponding PHPUnit tests in the php-chess/tests/unit/Eval/DeflectionEvalTest.php file.
Navigate to the php-chess/src/Eval folder in your project.

Create a new PHP file called DeflectionEval.php inside the Eval folder. This file will contain the implementation of the DeflectionEval feature.

Open the DeflectionEval.php file and define the DeflectionEval class. Implement the necessary evaluation logic for the deflection scenario within this class.

<?php
namespace Chess\Eval;

class DeflectionEval
{
    // Implement the evaluation logic for deflection scenario here
}

Save the DeflectionEval.php file.

Next, let's move on to writing the PHPUnit tests for the DeflectionEval feature:

Navigate to the php-chess/tests/unit/Eval directory.

Create a new PHP file called DeflectionEvalTest.php in the Eval folder. This file will contain the PHPUnit tests for the DeflectionEval class.

Open the DeflectionEvalTest.php file and define the DeflectionEvalTest class. This class will extend the PHPUnit\Framework\TestCase class.

php
Copy
<?php
namespace Chess\Tests\Unit\Eval;

use PHPUnit\Framework\TestCase;

class DeflectionEvalTest extends TestCase
{
    // Write your PHPUnit tests for DeflectionEval class here
}
Write individual test methods within the DeflectionEvalTest class to test different aspects of the DeflectionEval class. For example, you can write tests to ensure correct evaluation results for various deflection scenarios.

php
Copy
public function testDeflectionEvalScenario1()
{
    // Test deflection scenario 1
}

public function testDeflectionEvalScenario2()
{
    // Test deflection scenario 2
}

// Add more test methods as needed
Save the DeflectionEvalTest.php file.

That's it! You have now implemented the DeflectionEval feature in the php-chess/src/Eval folder and created the corresponding PHPUnit tests in the php-chess/tests/unit/Eval/DeflectionEvalTest.php file.

Make sure to fill in the implementation details and write appropriate tests based on your project requirements. If you need any further assistance or have any questions regarding the implementation, feel free to ask!

**Comment by KartikWatts** [comment]
Hi there, happy learning and coding!
I would to work on this, kindly assign it to me, if available. Regards.
