### ISSUE TITLE
TDD the Chess\Eval\BackRankEval class

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#467]
A new evaluation feature called `Chess\Eval\BackRankEval` needs to be implemented in the [php-chess/src/Eval](https://github.com/chesslablab/php-chess/tree/master/src/Eval) folder. The PHPUnit tests are to be written in the `php-chess/tests/unit/Eval/BackRankEvalTest.php` file accordingly.

See:

- [Back-rank checkmate](https://en.wikipedia.org/wiki/Back-rank_checkmate)

**Comment by gurpreetkaits** [comment]
Happy Learning !, are you working on it?

**Comment by gurpreetkaits** [comment]
@programarivm can we add some comments for abstract methods to make it easy to understand the action for someone who is building new functionality?

**Comment by programarivm** [comment]
Well I am of the opinion that comments shouldn't be necessary if the code is good, but let's elaborate on the issue. Shall we elaborate a list of about five classes requiring comments?

**Comment by gurpreetkaits** [comment]
@programarivm I have submitted the PR, I didn't check you have unassigned me.
