### ISSUE TITLE
TDD the Chess\Eval\OverloadingEval class

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#468]
A new evaluation feature called `Chess\Eval\OverloadingEval` needs to be implemented in the [php-chess/src/Eval](https://github.com/chesslablab/php-chess/tree/master/src/Eval) folder. The PHPUnit tests are to be written in the `php-chess/tests/unit/Eval/OverloadingEvalTest.php` file accordingly.

See:

- [Overloading](https://en.wikipedia.org/wiki/Overloading_(chess))

**Comment by gurpreetkaits** [comment]
I can open a PR for Tests, please notify me. I would love to contirbute.

**Comment by programarivm** [comment]
@gurpreetkaits welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/php-chess/blob/main/CONTRIBUTING.md).

I can't wait to see what you come up with!

**Comment by gurpreetkaits** [comment]
I'll go through, Thanks @programarivm

**Comment by programarivm** [comment]
@gurpreetkaits how are things going?

Here's a hint to solve the issue:

> A piece is overloaded when it is defending more than one piece at the same time.

I just realized that the overloading evaluation can be implemented by using the [defending()](https://github.com/chesslablab/php-chess/blob/main/src/Variant/AbstractPiece.php#L78) method implemented in `Chess\Variant\AbstractPiece`. This method returns an array containing the pieces defended by a piece, however, there isn't any unit test for that one method yet. 

So let's break down the problem into smaller pieces of complexity. Please let me know if you'd want to be assigned a different issue intended to write some unit tests for the pieces' `defending()` method.

I hope this helps,

**Comment by programarivm** [comment]
See https://github.com/chesslablab/php-chess/issues/575

**Comment by gurpreetkaits** [comment]
@programarivm , I am trying to create an app by using the lib so that I can understand the code and contribute. 

I'm reading/implementing along the way. So, I'll be creating a PR soon. Can we have a convo (just curious) on mail>
