### ISSUE TITLE
Ascii test the Fianchetto Variation of the Benoni Defense

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#47]
It'd be awesome if the sample chess openings could be tested in [`Chess\Tests\Unit\Fen\AsciiTest`](https://github.com/chesslablab/php-chess/blob/master/tests/unit/AsciiTest.php) as well by printing the ascii representation of the resulting board. This way the data can be visualized; thus, the [Fianchetto Variation of the Benoni Defense](https://github.com/chesslablab/php-chess/blob/master/tests/Sample/Opening/Benoni/FianchettoVariation.php) should be displayed as it is described next.

![board](https://user-images.githubusercontent.com/4062000/133931794-c18d7a58-2bbb-43da-aedb-b3f60bcf27c2.jpeg)

**Comment by programarivm** [comment]
hi @vikeng would you want to look at this issue within the next few days?

Thanks anyway, and happy learning and coding!

**Comment by vikeng** [comment]
@programarivm, I will look at this issue

**Comment by programarivm** [comment]
Thanks @vikeng I can't wait to see what you come up with! Keep it up.

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/php-chess/pull/51

This is okay, it looks like [all tests passed](https://app.travis-ci.com/github/chesslablab/php-chess). 

Thanks!
