### ISSUE TITLE
Castling is there while king has check

### ISSUE THREAD

**Issue by Mayank2001kh** [chesslablab/php-chess#471]
![image](https://github.com/chesslablab/chess-server/assets/72145584/b25931f7-9b2e-45ab-a2da-f559824ecd89)

According to rules castling is not allowed but its allowing castling.

I tried finding `/legal ` command  to resolve this but didn't undertood how its working can anyone help me in this?

**Comment by programarivm** [comment]
Thank you @Mayank2001kh for opening this issue. Happy learning!
