### ISSUE TITLE
Update a namespace

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#48]
This issue is aimed to practice software architecture and unit testing skills. 

Sometimes a particular file name or namespace needs to be changed. This is the case of the `Chess\Tests\Unit\Fen\AsciiTest` namespace, which should be updated to `Chess\Tests\Unit\AsciiTest` in order to keep a one-to-one correspondence between the file path and its corresponding namespace. 

Please replace `Chess\Tests\Unit\Fen` with `Chess\Tests\Unit` in the [`tests/unit/AsciiTest.php`](https://github.com/chesslablab/php-chess/blob/master/tests/unit/AsciiTest.php) file and make sure all tests pass after the update.

Happy learning and coding!

Keep it up.

**Comment by 11slartibartfast** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
@11slartibartfast, welcome to ChesslabLab.

Thank you for joining this community. 

The issue will be assigned to you on October 1st if this is okay.

Please let us know if you've got any questions.

Happy learning and coding!

**Comment by 11slartibartfast** [comment]
I'm new to the open source community and I would like to make one or two more contributions to this repo.
Thank you for assigning me this issue.

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/php-chess/pull/72
