### ISSUE TITLE
Implement the Figurine Algebraic Notation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#487]
An alternative to SAN is FAN (Figurine Algebraic Notation). FAN uses miniature piece icons instead of single letter piece abbreviations. The two notations are otherwise identical.

See:

- [Figurine Algebraic Notation (FAN)](https://www.chessprogramming.org/Algebraic_Chess_Notation#Figurine_Algebraic_Notation_.28FAN.29)

**Comment by KartikWatts** [comment]
Hi there, happy learning and coding!
Would absolutely love to contribute to this feature :) Kindly let me know these two points;
1. So we will simply use [Unicode characters](https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode#The_basic_12_chess_pieces) for our use case.. right.
2.  We can have another text class here: [ src/Movetext](https://github.com/chesslablab/php-chess/tree/main/src/Movetext) inheriting AbstractMovetext

Kindly let me know your thoughts @programarivm

**Comment by KartikWatts** [comment]
@programarivm Kindly assist me with the two properties in the `AbstractMovetext` class.

```php
abstract class AbstractMovetext
{
    public string $movetext;
    public array $moves;
   ... 
}
```

I just wanted to confirm the usage expectation, got confused a bit. I have a silly question, please bear:

- [ ] Will the `$movetext` as input be a FAN string like: `"1.d4 ♞f6 2.♘f3 e6"` and `$moves` as output be like: `[ 'd4', 'Nf6', 'Nf3', 'e6']`
OR converse
- [ ] `$movetext` be a string like: `"1.d4 Nf6 2.Nf3 e6"` and  `$moves` as `[ 'd4', '♞f6', '♘f3', 'e6']`

Could you please help me with this? Will clear the concept. Thanks and Regards.

**Comment by programarivm** [comment]
From the docs at [8.2.3: Movetext SAN (Standard Algebraic Notation)](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.2.3):

> FAN uses miniature piece icons instead of single letter piece abbreviations. The two notations are otherwise identical.

See https://github.com/chesslablab/js-utils/blob/main/src/common/Movetext.js#L23

One key feature of PHP Chess is that it has been designed with OOP principles in mind and is thoroughly tested with plenty of unit tests. The unit tests are the best documentation. They contain hundreds of real examples on how to use PHP Chess. Almost every class in the [src](https://github.com/chesslablab/php-chess/tree/main/src) folder represents a concept that is tested accordingly in the [tests/unit](https://github.com/chesslablab/php-chess/tree/main/tests/unit) folder, in other words, the structure of the tests/unit folder is mirroring the structure of the src folder. For further details on how to use `Chess\Movetext\SanMovetext` check out the corresponding tests in [tests/unit/Movetext/SanMovetextTest.php](https://github.com/chesslablab/php-chess/blob/main/tests/unit/Movetext/SanMovetextTest.php).

It seems as if a new class called `Chess\Movetext\FanMovetext` needs to be implemented.

I hope this helps.

**Comment by programarivm** [comment]
@KartikWatts the way to proceed is by TDDing the `Chess\Movetext\FanMovetext` class.

1. Write tests for `Chess\Movetext\FanMovetext` 
2. Implement `Chess\Movetext\FanMovetext`

`Chess\Tests\Unit\Movetext\FanMovetextTest` should be identical to [Chess\Tests\Unit\Movetext\SanMovetextTest](https://github.com/chesslablab/php-chess/blob/main/tests/unit/Movetext/SanMovetextTest.php) except that the letter piece abbreviations have been replaced with miniature piece icons as per https://github.com/chesslablab/js-utils/blob/main/src/common/Movetext.js#L23 

`Chess\Movetext\FanMovetext` should inherit from `Chess\Movetext\SanMovetext`

Happy learning!

**Comment by KartikWatts** [comment]
Following the discussion based on the created issue and js-utils implementation I have progressed with the development in the draft PR, please share your thoughts to ensure.
