### ISSUE TITLE
Implement the passed pawn evaluation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#49]
A passed pawn can definitely be a crucial advantage that determines the result of a chess game. 

As [Philidor](https://en.wikipedia.org/wiki/Fran%C3%A7ois-Andr%C3%A9_Danican_Philidor) once said: 

> "Pawns are the soul of chess."

This feature should be evaluated as it is described next.

- Every passed pawn has a value corresponding to the threat represented by its rank.

Examples:

![figure-01](https://user-images.githubusercontent.com/4062000/134060763-3ef03b07-f758-401d-b613-df9557946aea.jpeg)
**Figure 1**. w = 0, b = 4

![figure-02](https://user-images.githubusercontent.com/4062000/134060868-bc48c9c0-303c-4540-af9f-481ba3f7edb0.jpeg)
**Figure 2**. w = 0, b = 5 + 6

![figure-03](https://user-images.githubusercontent.com/4062000/134060985-20ca4e3c-d520-47d7-8586-8e1eb6b7fb82.jpeg)
**Figure 3**. w = 2, b = 0

---

Thus, a new file named `PassedPawnEvaluation.php` should be implemented in a similar way as the following evaluation features:

- [`CenterEvaluation.php`](https://github.com/chesslablab/php-chess/blob/master/src/Evaluation/CenterEvaluation.php)
- [`MaterialEvaluation.php`](https://github.com/chesslablab/php-chess/blob/master/src/Evaluation/MaterialEvaluation.php)

With the new feature implemented, we'll be in a position to take more accurate normalized heuristic pictures -- which will be addressed in a different issue:

- [Visualizing Chess Openings Before MLP Classification](https://medium.com/geekculture/visualizing-chess-openings-before-mlp-classification-fd2a3e8c266)

![figure-04](https://user-images.githubusercontent.com/4062000/134061323-9008452c-b34d-4fb2-b953-4747d578d7e7.png)
**Figure 4**. Heuristic picture after playing 1.e4 e6 2.d4 d5 3.e5 c5 4.c3 Nc6 5.f4 Qb6 6.Nf3 Nh6

Happy learning and coding!

**Comment by programarivm** [comment]
@vikeng if you'd want to look at this issue during October please feel free to give a ping and it'll be assigned to you.

It seems quite similar to [Implement the doubled pawn evaluation #50](https://github.com/chesslablab/php-chess/issues/50)

Anyway, thank you and keep it up!

**Comment by vikeng** [comment]
@programarivm assign me this issue.  I will look it at the weekend.

**Comment by programarivm** [comment]
Thank you! 

Let's officially assign it on October 1st as per [Hacktoberfest rules](https://hacktoberfest.digitalocean.com/) though.

I can't wait to see what you come up with.

**Comment by vikeng** [comment]
Hi, @programarivm! I sent  a commit for this issue. Assign me one more issue

**Comment by programarivm** [comment]
Merged PR https://github.com/chesslablab/php-chess/pull/61
