### ISSUE TITLE
@programarivm Could please send me (random vs random) code?

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#526]
@programarivm Could please send me (random vs random) code?

_Originally posted by @EarlyEdition in https://github.com/chesslablab/php-chess/issues/488#issuecomment-2079966404_

**Comment by EarlyEdition** [comment]
https://chessboardjs.com/examples#5002

I meant something like that.

**Comment by programarivm** [comment]
Let me elaborate on this one a bit. It seems as if an algorithm needs to be designed for this purpose. Here is how to make a random move from the start position.

```php
$board = new Board();

$legal = [];

foreach ($board->getPieces($board->getTurn()) as $piece) {
    if ($sqs = $piece->sqs()) {
        $legal[$piece->getSq()] = $sqs;
    }
}

$from = array_rand($legal);
shuffle($legal[$from]);
$to = $legal[$from][0];

echo "{$from}{$to}";
```

```txt
d2d4
```

See https://github.com/chesslablab/php-chess/blob/main/tests/unit/Variant/Classical/BoardTest.php#L46

**Comment by EarlyEdition** [comment]
@programarivm Could please invite me to @chesslablab?
