### ISSUE TITLE
Implementation of Chess\Play\RandomPlay

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#527]
`Chess\Play\RandomPlay` needs to be implemented in the [src/Play](https://github.com/chesslablab/php-chess/tree/main/src/Play) folder to play random games.

See https://github.com/chesslablab/php-chess/issues/526

**Comment by programarivm** [comment]
@EarlyEdition, the `Chess\Play` namespace is to host PHP components to play chess movetexts as per the PGN spec. 

Thus, the random chess player may well belong to the same category as `Chess\Grandmaster` in that these two are meant to make automatic chess moves programmatically. 

- `Chess\Computer\Random`
- `Chess\Computer\Grandmaster`
- `Chess\Computer\Abducer`

Probably, it makes sense to create a namespace called `Chess\Computer` intended for these kind of classes.

`Chess\Computer\Abducer` will be the next one to be added to this namespace. 

See: 

- [Chess Tutor](https://php-chess.docs.chesslablab.org/chess-tutor/)

> A heuristic evaluation is a quick numerical estimate of a chess position that suggests who may be better without considering checkmate. Please note that a heuristic evaluation is not the same thing as a chess calculation. Heuristic evaluations are often correct but may fail as long as they are based on probabilities more than anything else.

🎉 This is a form of abductive reasoning.

**Comment by EarlyEdition** [comment]
@programarivm, Thanks! I think it can be optimized in the future.
