### ISSUE TITLE
Write a unit test for the defending() method

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#575]
Write a unit test in [tests/unit/Variant/Classical/BoardTest.php](https://github.com/chesslablab/php-chess/blob/main/tests/unit/Variant/Classical/BoardTest.php) to demonstrate that the c3-pawn in the example attached is defending two pieces.

![screencapture-chesslablab-org-9443-en-edit-2024-07-19-19_23_02](https://github.com/user-attachments/assets/7bf1b2a3-adb3-49af-8d4a-ab3b5e7bf511)
**Figure 1**. 8/5k1r/5pp1/8/1N1B4/1KP5/8/8 w - -

Happy learning!

**Comment by KartikWatts** [comment]
Hi there, happy learning and coding!
If this is not assigned, I would love to work on this and start contributing to php-chess. Regards.
