### ISSUE TITLE
ELO calculator

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#580]
Let's just copy and adapt the [ELO Rating Generating Class](https://github.com/elijahcruz12/elo-rating-generator-php) by @elijahcruz12 into the `Chess\Eval` namespace.

See:

- https://github.com/chesslablab/chess-server/issues/370

**Comment by elijahcruz12** [comment]
As someone who used this package for a client, and happened to create that package for use with the same client, I'm going to say, you can have the code to be honest lol

I actually really liked using your package, so with that being said, feel free to take the code and do as you wish! ♥️

**Comment by programarivm** [comment]
Thank you @elijahcruz12 for the help.

May I ask one question about the `setScore()` method in [tests/unit/Elo/GameTest.php](https://github.com/chesslablab/php-chess/blob/main/tests/unit/Elo/GameTest.php)? Is this the total number of games played by each player?

Well done!

**Comment by elijahcruz12** [comment]
Set score if I remember correctly expect 0 or 1, and if it's 1, the player won, and if it's 0, the player lost, just for that game. I don't remember if I included stalemating however.
