### ISSUE TITLE
PSR-12 compliance in Chess\Computer

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#582]
Ensure the code in the [Chess\Computer](https://github.com/chesslablab/php-chess/tree/main/src/Computer) namespace is PSR-12 compliant.

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,
I would like to work on this issue. 
Please assign it to me if no one else is working on it.
Thanks!

**Comment by TheMarvelFan** [comment]
@programarivm ,

I have opened a PR. Please review the changes and let me know if any modifications are required. 

Thanks!
