### ISSUE TITLE
PSR-12 compliance

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#583]
Ensure the PHP code is PSR-12 compliant.

See:

- [WebCodeSniffer](https://www.webcodesniffer.net/)

---
- [x] https://github.com/chesslablab/php-chess/issues/582
- [x] https://github.com/chesslablab/php-chess/issues/584
- [x] https://github.com/chesslablab/php-chess/issues/585
- [x] https://github.com/chesslablab/php-chess/issues/586
- [x] https://github.com/chesslablab/php-chess/issues/587
- [x] https://github.com/chesslablab/php-chess/issues/588
- [x] https://github.com/chesslablab/php-chess/issues/589
- [x] https://github.com/chesslablab/php-chess/issues/590
- [x] https://github.com/chesslablab/php-chess/issues/591
- [x] https://github.com/chesslablab/php-chess/issues/592
- [x] https://github.com/chesslablab/php-chess/issues/593
- [x] https://github.com/chesslablab/php-chess/issues/594

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,

Is anyone working on any of these issues?
If not, I would like to take up all of them.

Thanks!

**Comment by programarivm** [comment]
@TheMarvelFan welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the Contributing Guidelines.

This is a list of issues. Issues are assigned by commenting on them separately one by one. Remember to submit up to 4 PRs between October 1 and October 31.

Happy learning and coding!
