### ISSUE TITLE
PSR-12 compliance in Chess\Eval

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#585]
Ensure the code in the [Chess\Eval](https://github.com/chesslablab/php-chess/tree/main/src/Eval) namespace is PSR-12 compliant.

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,
I would like to work on this issue. 
Please assign it to me if no one else is working on it.
Thanks!

**Comment by TheMarvelFan** [comment]
@programarivm 

I have created a PR for this issue. Please reiew the changes and let me know if any modifications are required.

**Comment by TheMarvelFan** [comment]
@programarivm 

I have created another PR as instructed. Please check it out and let me know if any further modifications are required.

Thanks!
