### ISSUE TITLE
PSR-12 compliance in Chess\Media

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#586]
Ensure the code in the [Chess\Media](https://github.com/chesslablab/php-chess/tree/main/src/Media) namespace is PSR-12 compliant.

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,
I would like to work on this issue. 
Please assign it to me if no one else is working on it.
Thanks!

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,

I have created a PR for this issue. Please review it and let me know if any further modifications are required.

Thanks!

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,

I have created a PR for this issue. Please review it and let me know if any further modifications are required.

Thanks!
