### ISSUE TITLE
PSR-12 compliance in Chess\UciEngine

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#588]
Ensure the code in the [Chess\UciEngine](https://github.com/chesslablab/php-chess/tree/main/src/UciEngine) namespace is PSR-12 compliant.

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,
I would like to work on this issue. 
Please assign it to me if no one else is working on it.
Thanks!

**Comment by programarivm** [comment]
Thank you @TheMarvelFan for your interest in contributing to this repo.

Let's solve the issues gradually one by one in groups of four.

I can't wait to see what you come up with!

**Comment by TheMarvelFan** [comment]
@programarivm 

Since there are mostly only minor changes in the code, should I create a single PR for 4 issues at a time, or should I create a different PR for each issue?
It would be simpler to have 1 per 4 issues.

**Comment by programarivm** [comment]
Thanks for asking this question.

As also discussed with @Neel-07 issues are solved one by one. 

See https://github.com/chesslablab/php-chess/pull/622

Keep it up,

**Comment by TheMarvelFan** [comment]
Understood.
I will create different PRs for each issue.

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,

I have created a PR to fix this issue. Please review the changes and let me know if any further modifications are required.

Thanks!
