### ISSUE TITLE
PSR-12 compliance in Chess\Variant\Chess960

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#591]
Ensure the code in the [Chess\Variant\Chess960](https://github.com/chesslablab/php-chess/tree/main/src/Variant/Chess960) namespace is PSR-12 compliant.

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,
I would like to work on this issue. 
Please assign it to me if no one else is working on it.
Thanks!
