### ISSUE TITLE
PSR-12 compliance in Chess\Variant\Dunsany

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#592]
Ensure the code in the [Chess\Variant\Dunsany](https://github.com/chesslablab/php-chess/tree/main/src/Variant/Dunsany) namespace is PSR-12 compliant.

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,
I would like to work on this issue. 
Please assign it to me if no one else is working on it.
Thanks!

**Comment by abdulmannans** [comment]
@programarivm  can you please assign me this so I can work on this.

**Comment by programarivm** [comment]
@abdulmannans welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the Contributing Guidelines.

Happy coding and learning!

**Comment by abdulmannans** [comment]
Welcome. Yes I will make sure of it.

**Comment by abdulmannans** [comment]
@programarivm can you please check.
