### ISSUE TITLE
PSR-12 compliance in Chess\Variant\RacingKings

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#594]
Ensure the code in the [Chess\Variant\RacingKings](https://github.com/chesslablab/php-chess/tree/main/src/Variant/RacingKings) namespace is PSR-12 compliant.

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,
I would like to work on this issue. 
Please assign it to me if no one else is working on it.
Thanks!

**Comment by TheMarvelFan** [comment]
Hi @programarivm ,

I have created a PR for this issue. Please review it and let me know if any further changes are required.

Thanks!
