### ISSUE TITLE
Writing code comments

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#595]
@programarivm can we add some comments for abstract methods to make it easy to understand the action for someone who is building new functionality?

_Originally posted by @gurpreetkaits in https://github.com/chesslablab/php-chess/issues/467#issuecomment-2365066058_

**Comment by programarivm** [comment]
Well I am of the opinion that comments shouldn't be necessary if the code is good, but let's elaborate on the issue. Shall we elaborate a list of about five classes requiring comments?

**Comment by gurpreetkaits** [comment]
It should be necessary at least for common methods, which can be used in any other classes as well. For example, if I'm building the BackRankEval feature, then moving to any parent class comments can give a better understanding in short.

**Comment by programarivm** [comment]
The evaluation classes in the [src/Eval](https://github.com/chesslablab/php-chess/tree/main/src/Eval) folder may definitely need comments. It'd be amazing if a brief description of the heuristic could be provided along with an explanation of how it has been implemented like in the example below.

> Deflection is a tactic that forces an opposing piece to leave an important square. Deflections are often used as part of a combination which involves other tactics as well, typically piece overloading and the back-rank checkmate.

See:

- https://github.com/chesslablab/php-chess/issues/458

As an example, you may want to check out [src/Variant/AbstractBoard.php](https://github.com/chesslablab/php-chess/blob/main/src/Variant/AbstractBoard.php).

Happy coding and learning!

**Comment by gurpreetkaits** [comment]
It makes a lot of sense.
