### ISSUE TITLE
Document Chess\Eval\DiscoveredCheckEval with comments

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#611]
Document [Chess\Eval\DiscoveredCheckEval](https://github.com/chesslablab/php-chess/blob/main/src/Eval/DiscoveredCheckEval.php) with comments to briefly explain the purpose of each part. Remember to write a brief description of the heuristic along with an explanation of how it has been implemented.

**Comment by vLeov** [comment]
Hey, can I do that?
And is it allowed to use copilot and change the answer if necessary?

**Comment by programarivm** [comment]
@vLeov welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the Contributing Guidelines.

It is allowed to use Copilot as long as the coding convention is the same one as used in the following example:

- [src/Eval/CenterEval.php](https://github.com/chesslablab/php-chess/blob/main/src/Eval/CenterEval.php)
- [src/Eval/CheckabilityEval.php](https://github.com/chesslablab/php-chess/blob/main/src/Eval/CheckabilityEval.php)

Happy coding and learning!
