### ISSUE TITLE
Allow to flip the chessboard when creating an image

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#87]
At the present moment, the `create()` method in [`Chess\FEN\StringToBoard`](https://php-chess.readthedocs.io/en/latest/image-board-to-png/) can generate a chessboard image from white side only, however it should generate an image from black side as well.

A second argument needs to be added to the [`Chess\FEN\StringToBoard`](https://php-chess.readthedocs.io/en/latest/image-board-to-png/) class constructor to allow flipping the board as it is described next.

```
use Chess\FEN\StringToBoard;
use Chess\Image\BoardToPng;

$board = (new StringToBoard('1rbq1rk1/p1b1nppp/1p2p3/8/1B1pN3/P2B4/1P3PPP/2RQ1R1K w - - bm Nf6+'))
    ->create();

$flip = true;

(new BoardToPng($board, $flip))->output('01_kaufman.png');
``` 
Happy learning and coding.

**Comment by programarivm** [comment]
Hi @vikeng, 

Today I've been looking at this issue and realized the `flip()` method should actually be implemented in [`Ascii.php`](https://github.com/chesslablab/php-chess/blob/master/src/Ascii.php) so it can be used in [`Chess\Image\BoardToPng`](https://github.com/chesslablab/php-chess/blob/master/src/Image/BoardToPng.php) in a similar way as described in the following example.

```
$ascii = new Ascii();

if ($flip) {
    $ascii->toArray($this->board)->flip();
} else {
    $ascii->toArray($this->board);
}
```

Please let me know if this makes sense, and keep it up.

Thanks!

**Comment by vikeng** [comment]
HI @programarivm,
In order for this to work
$array = $ascii->toArray($this->board)->flip();
the method toArray needs to return Ascii now returns array.
Maybe I do so 
$array = $ascii->toArray($this->board,$flip)
public function toArray(Board $board, bool $flip=false): array
