### ISSUE TITLE
Image test the Open Sicilian

### ISSUE THREAD

**Issue by programarivm** [chesslablab/php-chess#94]
The sample chess openings should be tested in [`Chess\Tests\Unit\Image\BoardToPngTest`](https://github.com/chesslablab/php-chess/blob/master/tests/unit/Image/BoardToPngTest.php) by creating an image of the resulting flipped board. This way the data can be visualized; for example, the [Fianchetto Variation of the Benoni Defense](https://github.com/chesslablab/php-chess/blob/master/tests/Sample/Opening/Benoni/FianchettoVariation.php) is displayed as it is described next.

![benoni_fianchetto_variation_flip](https://user-images.githubusercontent.com/4062000/137629263-f4f86040-1cbb-4e78-b88f-a9f991c4bb6b.png)
**Figure 1**. Fianchetto Variation of the Benoni Defense

For further information, please visit:

- [How to Unit Test Automatically Generated Images](https://programarivm.medium.com/how-to-unit-test-automatically-generated-images-e8cd1fb668a8)

**Comment by Visovsiouk** [comment]
@programarivm Thanks for the info, I've created a pull request.
